balena-io-modules/balena-request

README.md
build/utils.js
lib/utils.coffee
package.json
tests/request.spec.coffee
tests/utils.spec.coffee

Means passing the token option to request() is now unnecessary.

Use resin-token to retrieve the authentication token

---

build/utils.js
lib/utils.coffee
package.json

Piping directly makes the process exit after ~10s.

Manually pipe data from the download to options.pipe

---

README.md
build/request.js
build/utils.js
lib/request.coffee
lib/utils.coffee
tests/request.spec.coffee
tests/utils.spec.coffee

Accepting onProgress as the last argument breaks the NodeJS convention
where the last argument is supposed to be the callback.

Read onProgress function from the options object

---

build/request.js
lib/request.coffee
tests/request.spec.coffee

When streaming an HTTP request, if the response contains a
`Content-Length` header, parse it and use it as the `length` property.
This `length` property is used by Resin Image Write to emit correct
progress information when piping a download directly to a drive.

Use Content-Length value as stream.length

---

README.md
build/request.js
lib/request.coffee

This property is used to determine the length of the stream to create a
meaningful progress bar.

Document custom `.length` property

---

README.md
build/request.js
lib/request.coffee
tests/request.spec.coffee

The addition of this property is helpful for later deciding whether to
uncompress the stream or not, without having to detect the mime type
manually.

Implement custom .mime property based on Content-Type

---

build/estimate.js
lib/estimate.coffee
tests/estimate.spec.coffee

Currently, `request-progress` emits a progress event containing a
`percent` property, however Resin CLI Visuals and Resin Image Write call
this property `percentage`.
For consistency reason, we convert `percent` to `percentage` here.

Translate percent to percentage in progress event

---

README.md
build/request.js
lib/request.coffee
tests/request.spec.coffee

Decouple Resin Request from the environment by requiring the api key to
be passed as an option instead of reading as an environment variable
directly.

Accept apikey as an option

---

build/request.js
lib/request.coffee
tests/request.spec.coffee

Currently, if the user passed custom query strings, those would override
the apikey query. They should be merged together instead.

Merge apikey with custom query strings

---

build/utils.js
lib/utils.coffee

The `X-Transfer-Length` stands for *compressed* transfer length while
`Content-Length` represents the *uncompressed* counterpart.
This means we have to pipe compressed or uncompressed data to the client
accordingly.
Fixes: https://github.com/resin-io/resin-cli/issues/267

Pipe uncompressed data if no X-Transfer-Length

---

build/progress.js
build/request.js
build/utils.js
lib/progress.coffee
lib/request.coffee
lib/utils.coffee
package.json
tests/request.spec.coffee
tests/utils.spec.coffee

There was a subtle issue about how we treated compressed requests that
contain a `X-Transfer-Length` header.
This header equals the size of the body in it's *compressed* form. We
were currently treating this value as the total value of the download
and consuming the compressed data stream from `node-request`, resulting
in the download being saved without decompression.
The fix is to check whether `Content-Encoding: gzip` is set to determine
if the content is being received in a compressed form, disabling
automatic `gzip` compression on `node-request` and handling
decompression manually with `zlib`.
By handling decompression ourselves, we can choose to perform this step
after or before checking the stream progress, allowing us to decompress
depending on the total size of the progress being …

Fix X-Transfer-Length decompression bug

---

build/request.js
lib/request.coffee

> If true, requires SSL certificates be valid. Note: to use your own
> certificate authority, you need to specify an agent that was created
> with that CA as an option.
https://github.com/request/request#requestoptions-callback

Enable strictSSL by default

---

build/request.js
lib/request.coffee

Gzip was disabled due to the need of finer control when manipulating
compressed responses from `request.stream`.
This is however not needed for normal requests, where disabling gzip
hurts performance.

Only disable gzip on stream requests

---

README.md
build/progress.js
build/request.js
lib/progress.coffee
lib/request.coffee
tests/request.spec.coffee

Remove .length stream property

---

build/request.js
lib/request.coffee
tests/request.spec.coffee

Newer versions of the Resin SDK will make use of this option to decouple
`resin-request` from SDK settings.

Support passing a baseUrl option

---

build/utils.js
lib/utils.coffee
tests/utils.spec.coffee

This setting is too low level for users to have any reason for customise
it, and the value hugely depends on the expiry time set by the Resin
API, therefore having it under our control prevents broken applications
by Resin modifying the expiry time and a user keeping an old
configuration.

Hardcode tokenRefreshInterval setting

---

build/request.js
lib/request.coffee

This default option previously lived in `resin-pine`, but its nicer to
move it here so `resin-pine` and any other clients get it automatically.

Set a default timeout of 30s

---

build/request.js
lib/request.coffee
package.json
tests/request.spec.coffee

If there is a saved token that needs to be refreshed, but it already
expired, the client will get a 'Not Authorized' error.
We can catch this corner case by inspecting the response of the
`GET /whoami` request, which is issued to refresh the token. If the
resulting status code is `401`, we know it represents an scenario where
the token is expired.
Fixes: https://github.com/resin-io/resin-cli/issues/318

Throw an informative error when the token is expired

---

build/request.js
lib/request.coffee
tests/request.spec.coffee

Currently we throw an error if the token is expired, but keep it there.
The CLI intercepts this error and prints a friendly message asking the
user to login with `resin login`, however this command will attempt to
make some HTTP requests before performing the login, which will throw
the expired error again, and will ask the user to run `resin login` when
actually running `resin login`.

Remove saved token if its expired

---

build/request.js
lib/request.coffee
tests/api-key.spec.coffee

We've encountered a weird edge case where if we pass an `undefined`
query string to `request`, like
```json
{
"qs": {
"api_key": undefined
}
}
```
It will cause `request` to URL-encode any special character in the URL
after the query question sign.
So for example, `/foo?$bar=baz` would become `/foo?%24bar=baz`, and thus
will fail to match the intended route.

Prevent passing an undefined api_key query string

---

README.md
build/request.js
lib/request.coffee
package.json
tests/api-key.spec.coffee
tests/request.spec.coffee
tests/stream.spec.coffee
tests/token.spec.coffee

This PR is part of the process of refactoring the Resin SDK to decouple it
from the environment to easy porting it to the browser.

Decouple resin-request from resin-settings-client

---

.travis.yml
CHANGELOG.md
README.md
appveyor.yml
doc/README.hbs
karma.conf.coffee
package.json

And now finally we have a browser-compatible resin-request module.
It refers to the github version of resin-token, I will update that when the new version is released.

update resin-token and add browser tests runner

---

CHANGELOG.md
build/request.js
build/utils.js
lib/request.coffee
lib/utils.coffee
tests/request.spec.coffee
tests/setup.coffee

Adds a 'retries' option you can pass to `send()`, which sets the number of times to retry this request (defaulting to 0).
This is part of the fix for resin-io/resin-sdk#237.

Optionally retry requests

---

CHANGELOG.md
build/utils.js
lib/utils.coffee

Nice simple one: just adds 'duration' to the log output, so that for resin-io/resin-sdk#237 we can easily start examining how long requests are actually taking.

Track request time and include it in output when debug mode is enabled

---

build/utils.js
lib/utils.coffee

Found [`.timeout`](http://bluebirdjs.com/docs/api/timeout.html) this while implementing resin-io/resin-register-device#27. Pretty sure it's equivalent to the behaviour we've defined here (except we incorrectly call reject twice on errors, but that doesn't do anything).

Use bluebird's built in timeout support rather than implementing our own

---

CHANGELOG.md
README.md
build/utils.js
doc/README.hbs
lib/utils.coffee
package.json
tests/api-key.spec.coffee
tests/request.spec.coffee
tests/setup.coffee
tests/token.spec.coffee
tests/utils.spec.coffee

This ended up being drastically harder than the equivalent register-resin-device change (see https://github.com/resin-io-modules/resin-register-device/pull/27), but it's now all working. Some caveats:
* There's quite a few workarounds for various `fetch-mock` issues, leading to some remaining strange and wonderful setup code for that in `setup.coffee`. Everything elsewhere comes out nicely though, and I've filed a couple of issues and linked them inline, so we can improve this later as they get solved.
* Mockery works fine in Node, but getting any mocking working in Browserify without breaking Node  became a huge pain, and I've opted for the far simpler option: exposing `utils.fetch`, and letting you change it externally. Less elegant, and I'd welcome an improvement on that if anybody has …

Use fetch-ponyfill instead of requiring isomorphic-fetch downstream

---

CHANGELOG.md
build/utils.js
lib/utils.coffee
tests/request.spec.coffee

This fixes #83.
When I added the tests for this, I noticed that somewhere along the way we've actually broken timeouts in resin-request completely. The default 30s timeout is ignored, and any manually passed timeout options are ignored, because we drop them in `processRequestOptions`.
This patch fixes that. It also now passes the `timeout` option to the fetch call (so that `node-fetch` [forcefully cancels the underlying request](https://github.com/bitinn/node-fetch/blob/3c053ce32760d2d5d6cb8712fb4115b44e4083d4/index.js#L125)) and only sets the extra bluebird non-canceling timeout if you're in a browser (where fetch can't be cancelled).

Fix broken timeout functionality, and cancel underlying requests where possible

---

CHANGELOG.md
README.md
build/request.js
doc/README.hbs
lib/request.coffee
package.json
tests/setup.coffee

This moves Resin-Request to DI, as discussed in resin-io-modules/resin-request#85

Move to a DI approach for resin-token

---

build/utils.js
lib/utils.coffee

Having put out 8.0.0 and integrated it everywhere, when I finally got to the SDK where the tests actually use it to make real requests, it doesn't actually work at all.
That tiny _ prefixing fix from yesterday means the fetch-ponyfill import doesn't actually work at all any more, and exports.fetch is always `undefined`. That issue gets completely hidden by the tests, since they always replace it anyway.
Now fixed. I've manually pulled this version into my Resin-SDK locally too, and it seems to now work nicely. Once somebody approves, I'll merge this, deprecate 8.0.0, and put out an 8.0.1 that actually works.

Fix tiny bug that breaks everything, except in the tests

---

CHANGELOG.md
build/utils.js
lib/utils.coffee

Outside the browser this is correct, but in a browser the encoding process is outside our control, and the browser just ignores it and logs a warning:
> Refused to set unsafe header "accept-encoding"
This would be a breaking change if the original code had any effect, but since [the spec](https://fetch.spec.whatwg.org/#forbidden-header-name) says all browsers must ignore it, it's just a patch.

Don't try to automatically add an 'accept-encoding' header in the browser

---

CHANGELOG.md
build/request.js
lib/request.coffee
package.json
tests/hooks.spec.coffee

This ensures that whenever an error is thrown from an issue with a request, we include the request config with it - either by manually attaching it if `fetch` throws an exception itself (seems to throw a TypeError with `failed to fetch` typically), or by passing it to the constructor if we build our own `ResinRequestError`. I've nested the catch so we only do this with actual request errors, not any possible error that reaches this point. I'm a bit cautious of messing with the unknown exceptions that other interceptors might throw, or that we might get in our pre-request options & auth setup code.
This is building on top of https://github.com/resin-io-modules/resin-errors/pull/14, and is again part of https://github.com/resin-io/resin-ui/issues/400.
I considered moving all request errors …

Include request options in request errors

---

CHANGELOG.md
build/request.js
lib/request.coffee

`name` depends on the actual name of the class, which changes during minification. In this case, resin-ui would catch errors correctly in dev, but not in staging/production (as name was `t`). `code` meanwhile is reliable, so we should use that instead.
This is another fix out of resin-io/resin-ui#714.

Fix bug with token error handling when code is minified

---

circle.yml
package.json

Stops using circleCI for npm deploys.
No longer runs the tests before publishing, since that resinCI
step is meant to be really slim and also the image used doesn't
have Chrome installed (see attached discussion).
Should not be a concern since:
* the tests were run before merging to master
* we are moving away from manual publishing.
ResinCI requires zero configuration so most of the time
there is no reason to publish anything manually.
Resolves: #126
See: https://www.flowdock.com/app/rulemotion/r-beginners/threads/fnuvWdmMTYdgY4sAitqaYvA0-f3
Signed-off-by: Thodoris Greasidis <thodoris@resin.io>

Use resinCI for publishing to npm

---

package.json

This brings in the changes from https://github.com/jonnyreeves/fetch-readablestream/pull/7. This should meant that abort is now fully supported in modern browsers, so they will totally close the backing request streams that are opened when viewing logs (rather than just stopping listening to them).

Update to new fetch-readablestream that properly supports abort()

---

package.json

This was probably missed during the rename PR.
It seems that we updated the devDependency to v3
and missed to also update the version for the
peerDependency.
PS: balena-auth starts with v3.
Resolves: #133
See: https://github.com/balena-io-modules/balena-request/pull/129/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R47
See: https://github.com/balena-io/balena-sdk/issues/663

Fix invalid balena-auth peer dependency

---

.gitignore

It seems that this was forgotten while doing https://github.com/balena-io-modules/balena-request/pull/136/commits/793f2f4104a06d8a2fe019a537350b1f6cf413e3

Add the build directory to the .gitignore

---

lib/request.js

Fix passing baseUrl to refreshToken if the request uses an absolute url

---

lib/request.js
tests/hooks.spec.coffee
tests/token.spec.coffee

Essentially reverting v11.0.1 but rejecting with a
better error than before.
See: https://www.flowdock.com/app/rulemotion/resin-frontend/threads/XVvB7BhMFMXAXsQNwACFg5seFyQ
See: https://github.com/balena-io/balena-ui/issues/3942

Stop refreshing the token on absolute urls

---

package.json

Update balena-errors from 4.4.0 to 4.7.1
Required by balena-io/balena-cli#2050
Depends-on: https://github.com/balena-io-modules/balena-auth/pull/26

Update balena-auth from 4.0.0 to 4.1.0

---

lib/request.js
tests/token.spec.coffee

Minor since that endpoint was available on balenaCloud way before our latest major release (v11) and none of the two are at the moment available in open-balena.
See: https://github.com/balena-io/balena-api/blob/509ab434d9b52a9649955df2a212c87bf4e82d0e/src/routes/index.ts#L35-L40
See: https://github.com/balena-io/balena-api/blob/509ab434d9b52a9649955df2a212c87bf4e82d0e/src/routes/index.ts#L225-L230

Switch to the versioned token refresh endpoint

---

package.json

The only breaking change is dropping support
for node v8 but we have already done that in v11.
See: https://github.com/qubyte/fetch-ponyfill/blob/main/HISTORY.md#700

Update fetch-ponyfill to v7

---

lib/progress.js

Signed-off-by: Kyle Harding <kyle@balena.io>

Allow overriding the default zlib flush setting

---

lib/utils.ts

Use response error as response message if there is one
Connects-to: https://github.com/balena-io/balena-ui/pull/5427
Signed-off-by: Matthew Yarmolinsky <matthew-timothy@balena.io>

Use response error as response message if there is one

---

lib/utils.ts

Current behaviour of trying to refresh the token after it has lived for 1 hour is too aggressive, and for non refreshable tokens with smaller TTL it might generatae undesired behaviour such as trying to renew the token (and failing) on all requests, so we decided to increase this interval and the client can renew it themselves more frequently if necessary.

Increase TOKEN_REFRESH_INTERVAL from 1 hours to 1 day

---

lib/progress.ts
lib/utils.ts
tests/request.spec.ts
tests/response-format.spec.ts
tests/utils.spec.ts

Allows us to cast the result of the fetch a bit earlier and re-uses the timeout helper that we have in the UI.
See: https://balena.fibery.io/Work/Project/Use-native-fetch-for-non-streaming-requests-1568

Abstract the timeout implementation
