balena-io-modules/balena-request

build/request.js, lib/request.coffee, tests/request.spec.coffee
Sometimes, when piping the download of an image to a file, we got the
following error from Resin Request:
You cannot pipe after data has been emitted from the response.
I was able to capture this in an unit test by adding a delay between the
stream being returned and the client attempting to read data from it.
This means we attempted to pipe the data after it was emitted initially
from the response, thus the error above makes sense.
The solution:
- Quickly pipe the `node-request` stream to a `PassThrough` stream, and
return that instead.
- In order to avoid breaking changes, we had to manually pipe the
`response` event from `node-request` to the `PassThrough` stream.
Side effects:
- I was able to remove the ugly `download.on()` stub to inject the
estimator.
- Cleaned up some tests to use …
=> Fix random error when piping a stream

build/request.js, lib/request.coffee, package.json, tests/request.spec.coffee
This is very useful for debugging purposes.
=> Set statusCode in ResinRequestError

.travis.yml, README.md, build/request.js, lib/request.coffee, tests/api-key.spec.coffee, tests/request.spec.coffee, tests/stream.spec.coffee, tests/token.spec.coffee
This PR also introduces some minor test changes necessary for the test suite to run correctly.
=> Add support for API keys

build/utils.js, lib/utils.coffee
=> Small post-merge review markups

CHANGELOG.md, package.json
Depends on https://github.com/jviotti/rindle/pull/5
=> Update rindle so that bluebird and lodash can be deduped

CHANGELOG.md, build/request.js, build/utils.js, lib/request.coffee, lib/utils.coffee
Missed this spot from the other PR, but with this the token becomes completely optional
=> Don't try to resolve the token when none is provided

karma.conf.coffee
Depends-on: https://github.com/resin-io/resin-concourse/pull/248/
Signed-off-by: Thodoris Greasidis <thodoris@resin.io>
=> chore: Add headless Chrome parameters to work on ResinCi

package.json
=> Update github target

lib/progress.coffee, package.json
=> Use @balena/node-web-streams instead of a GitHub branch

package.json
=> Fix tslib dependency

lib/request.js
=> Fix body overwriting on nodejs

lib/progress.js, lib/request.js
=> Add lazy loading for most modules

lib/request.js, tests/token.spec.coffee
=> Prevent token refresh when no base url is provided

package.json
=> Drop explicit karma-chrome-launcher devDependency

lib/request.ts, lib/utils.ts, package.json
=> Fix the typings to proprly mark the auth parameter as optional

karma.conf.js
=> Fix overriding the whole webpack resolve section of karma tests

package.json
=> Update balena-auth to 5.0.0

karma.conf.js, package.json
=> Make `url` a normal dependency

lib/request.ts, package.json, tests/request.spec.js
Depends-on: https://github.com/balena-io-modules/balena-errors/pull/54
=> Include the response headers in BalenaRequestErrors

lib/progress.ts, lib/request.ts, lib/utils.ts, tests/token.spec.js
=> fix: throw BalenaExpiredToken only when token is really expired

package.json
Update balena-auth from 5.1.0 to 6.0.1
=> Update balena-auth to 6.0.1

package.json, tests/api-key.spec.ts, tests/browserify-zlib.ts, tests/hooks.spec.ts, tests/request.spec.ts, tests/response-format.spec.ts, tests/setup.ts, tests/stream.spec.ts, tests/token.spec.ts, tests/utils.spec.ts, tsconfig.json
=> Tests: Convert to typescript

karma.conf.js, lib/conditional-imports.browser.ts, lib/conditional-imports.ts, lib/progress.ts, lib/utils.ts, package.json
=> Avoid requiring some node dependencies using the package.json browser field

lib/utils.ts
=> Clear created setTimeout
